### ISSUE TITLE
Setting up the first kanban board project for react

### ISSUE THREAD

**Issue by aradradev** [Rifat8080/react-redux-group-project#58]
In this project we have done the processing below:

- We installed the choco and copied the Kanban board
- Initialised a new Todo list.
- Assigned tasks for each member(We are two members @Rifat8080 && @aradradev )

Link to the project Kanban: https://github.com/Rifat8080/React-Redux-Group-Project/projects/3

**Comment by AmaduKamara** [comment]
# Status: Approved 🟢 🟢 🟢

Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ Set up Kanban Board correctly 👍🏽 
✅ Tasks are shared fairly 👍🏽
✅ Add description for all tasks 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
